### ISSUE TITLE
Profile index page is slow

### ISSUE THREAD

**Issue by relaxnow** [OpenConext/OpenConext-engineblock#105]
The Profile index page does a getArp request and applies the ARP for ALL Service Providers and then sees which ones it actually needs to display.
This is only performant because when all getArp calls are cached. Given that we may want to switch metadata sources to a database it is advisable to optimise this.

**Comment by thijskh** [comment]
This is actually pretty annoying because the load time when there is no cache results in a gateway timeout. Given that the cache is cleaned out several times a day this occurs with significant frequency.

It may be mitigated for SURFconext when 150 unused test SP entries are dropped next week, but the issue definitely needs addressing.

**Comment by relaxnow** [comment]
Response times on my vm with a user that has given consent to 2 SPs:

```
120      - without patch without cache
    0.75 - without patch with cache

    2.5 - with patch without cache
    0.75 - with patch with cache
```

**Comment by thijskh** [comment]
:+1:
