### ISSUE TITLE
SUR-401 XML Signature exclusion

### ISSUE THREAD

**Issue by relaxnow** [OpenConext/OpenConext-engineblock#123]
It is possible to delete the outer signature from the SAML response and successfully login. However, impact is reduced because the decrypted SAML assertion also contains a signature.
Threat Level: Low

**Comment by relaxnow** [comment]
This is currently a feature we offer to Identity Providers, though maybe we want to make this more explicit by having a Service Registry setting for this (which we enable for all legacy Identity Providers)? Though I don't think we'll be getting a lot more Identity Providers?
@thijskh, @pmeulen thoughts?

**Comment by thijskh** [comment]
The SAML spec contains a myriad of security-related options and features, and any implementation makes a choice of which it wants to use. We've chosen to use the signature on the assertion to verify the authenticity of an encrypted assertion which makes the process in our constellation of features a secure one. You could even argue that it's more secure than actually using the outer signature, since one of the benefits of encrypted assertions is that your signature doesn't leak.

All in all this is not a security problem (as the auditors acknowledge), just a selection of which of the many available security features we use. I think no further action is needed at this point.
