### ISSUE TITLE
SUR 404 IssueInstant in response not processed

### ISSUE THREAD

**Issue by relaxnow** [OpenConext/OpenConext-engineblock#124]
SUR 404 Issuerinstant in response not processed
The SP does not verify the IssueInstant Attribute within the Response Element.
Threat Level: Low

**Comment by thijskh** [comment]
As described in the report this is not a vulnerability as the field is not used in a security-relevant way. In fact, I think we're not doing anything with this information and it's purely informational-only for those inspecting the SAML messages. So I'm not sure that doing explicit validation on it adds something other than lines of code.

The SAML2 library does parse it into a timestamp so it at least verifies that it's a valid datetime string, but as far as I can see does not otherwise use it aswell.
