### ISSUE TITLE
Show certificate fingerprint on web page

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-engineblock#153]
It would be nice if the default engien website (https://engine.openconext.org) would show the certificate fingerprint next to the metadata and the full cert.

**Comment by thijskh** [comment]
This requires extra processing of the certa for rendering the index page. Not sure I’d prefer that, esp since I think it’s much better to use the certs themselves rather than fingerprints. If you want it, you can now easily change the twig template. With that extra flexibility now I consider this not a priority.
