### ISSUE TITLE
Updating database metadata takes 15 seconds for 1000+ entities

### ISSUE THREAD

**Issue by relaxnow** [OpenConext/OpenConext-engineblock#268]
The current implementation does not wipe the table (TRUNCATE) and create an all new table but does updates to bring EBs metadata up to date this is a relatively slow process and is not really needed as EB always expects a complete dump with all metadata.

**Comment by thijskh** [comment]
It currently takes about 20 seconds. A lot of infrastructure around this has already been removed. I'm not sure about the proposed approach, since that would render EB without a database for a short moment which is evidently undesirable. The current approach of updating rows in-place is slow for the person updating EB but keeps all logins flowing while it happens, which is much more important.
