### ISSUE TITLE
Strange issue with WAYF

### ISSUE THREAD

**Issue by arnoutt** [OpenConext/OpenConext-engineblock#292]
Unfortunately, I don't know how to reproduce this. Please see attached screenshot.

![screen shot 2016-04-15 at 11 52 37](https://cloud.githubusercontent.com/assets/8791564/14562925/a6874ea6-031f-11e6-9614-b59519c480a2.png)

The debug console outputs this:

> Blocked script execution in
> 'https://engine.surfconext.nl/authentication/idp/single-sign-on?SAMLRequest=…woALsWEwDloi6Ev%2b%2fQf0L&RelayState=4c3503b8-b9e3-4dc8-873f-39771eeed79f#'
> because the document's frame is sandboxed and the 'allow-scripts'
> permission is not set.
> chrome-extension://gofhjkjmkpinhpoiabjplobcaignabnl/content.js:346
> Blocked script execution in
> 'https://engine.surfconext.nl/authentication/idp/single-sign-on?SAMLRequest=…woALsWEwDloi6Ev%2b%2fQf0L&RelayState=4c3503b8-b9e3-4dc8-873f-39771eeed79f#'
> because the document's frame is sandboxed and the 'allow-scripts'
> permission is not set.setBlockCSSStyle @
> chrome-extension://gofhjkjmkpinhpoiabjplobcaignabnl/content.js:346
> /authentication/idp/single-sign-on?SAMLRequest=fZJLa8MwEIT%2fitFdlp04DwvHEB…ALsWEwDloi6Ev%2b%2fQf0L&RelayState=4c3503b8-b9e3-4dc8-873f-39771eeed79f#:1
> Blocked script execution in
> 'https://engine.surfconext.nl/authentication/idp/single-sign-on?SAMLRequest=…woALsWEwDloi6Ev%2b%2fQf0L&RelayState=4c3503b8-b9e3-4dc8-873f-39771eeed79f#'
> because the document's frame is sandboxed and the 'allow-scripts'
> permission is not set.
> SVG's SMIL animations (&lt;animate&gt;, &lt;set&gt;, etc.) are deprecated and will
> be removed. Please use CSS animations or Web animations instead.
> 18/authentication/idp/single-sign-on?SAMLRequest=fZJLa8MwEIT%2fitFdlp04DwvHEB…ALsWEwDloi6Ev%2b%2fQf0L&RelayState=4c3503b8-b9e3-4dc8-873f-39771eeed79f#:1
> Blocked script execution in
> 'https://engine.surfconext.nl/authentication/idp/single-sign-on?SAMLRequest=…woALsWEwDloi6Ev%2b%2fQf0L&RelayState=4c3503b8-b9e3-4dc8-873f-39771eeed79f#'
> because the document's frame is sandboxed and the 'allow-scripts'
> permission is not set.

**Comment by baszoetekouw** [comment]
Het lijkt alsof er in de pagina ergens een iframe zit, om de een of andere reden.  En de error over "SVG's SMIL animations" vind ik ook nogal gek.

Waar kreeg je dit precies?

Zie ook http://stackoverflow.com/questions/24453898/why-am-i-getting-a-blocked-script-execution-error/24506178?stw=2#24506178

**Comment by thijskh** [comment]
The WAYF has no iframe. The error messages suggest that a browser extension is used where this error occurs: `chrome-extension://gofhjkjmkpinhpoiabjplobcaignabnl/content.js:346`, that's not a location in our code but in the extension's code.

I'd recommend reporter to look into the mentioned extension (not sure if you can deduce that from the string; otherwise disable all plugins, then re-enable one by one until the problem reappears) so we know which extension is the culprit.

As for the SVG deprecation warning, that seems correct (after I fixed the above text); we use SVG animation in the spinner. But it's a deprecation warning, not an error.
view-source:https://engine.surfconext.nl/images/spinner.svg
We might want to fix that sometime.

**Comment by DRvanR** [comment]
> (not sure if you can deduce that from the string; otherwise disable all plugins, then re-enable one by one until the problem reappears)

Fairly easy to find actually: go to `chrome://extensions/`, this is a listing of all installed (enabled and disabled) extensions. Each has an `ID`. The extension that creates the error has the ID `gofhjkjmkpinhpoiabjplobcaignabnl`.

**Comment by thijskh** [comment]
Not likely an Engineblock issue.
