### ISSUE TITLE
Error running composer.phar

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/OpenConext-engineblock#341]
When manually installing from current master-branch, running bin/composer.phar results in the following error:

PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /apps/openconext-engineblock/engineblock-dev/src/OpenConext/EngineBlockBundle/DependencyInjection/OpenConextEngineBlockExtension.php on line 89

Seems like Feature::class is not correct and should be a string.

**Comment by arothuis** [comment]
Thanks for reporting this. 

Which PHP version are you using? 
`::class` is supported since [PHP 5.5][2], EngineBlock 5.x [requires PHP 5.6+][1].

[1]: https://github.com/OpenConext/OpenConext-engineblock#system-requirements
[2]: http://php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class

**Comment by tvdijen** [comment]
Ah, crap, I think 5.4 is the default on CentOS 7. I will verify this tonight.

**Comment by thijskh** [comment]
Yes. We use the remi repository to install 5.6 on Centos 7. https://github.com/OpenConext/OpenConext-deploy/blob/engineblock5-centos7/roles/php56fpm/tasks/main.yml

**Comment by tvdijen** [comment]
Okay, confirmed. Case closed.
