### ISSUE TITLE
JS error in Onedrive built-in browser prevents logging in

### ISSUE THREAD

**Issue by thijskh** [OpenConext/OpenConext-engineblock#351]
Using Onedrive with the built-in browser generates a JS error in the WAYF, it's not possible to select the IdP for these users. The referenced line and char numbers are in EB 5.0.0.

<img width="463" alt="capture" src="https://cloud.githubusercontent.com/assets/3808792/19764999/5bbed82e-9c46-11e6-81c0-819840854775.PNG">

**Comment by arothuis** [comment]
I'm not familiar with that browser and am having trouble finding more information about which browser is used internally (as in: which standards are used). Replication of the bug seems difficult on a Mac (unless I use a Windows VM and install OneDrive).

There is a chance this is fixed with the new WAYF as that has extended support for older browsers. 

The jQuery-related code that starts at the line and character referred to by the cited Script Error is, deminified, as follows (starting at "f" of "for:"):
```
({
    propFix: {for: "htmlFor", class: "className"}, prop: function (a, b, c) {
        var d, e, f, g = a.nodeType;
        if (a && 3 !== g && 8 !== g && 2 !== g)return f = 1 !== g || !ea.isXMLDoc(a), f && (b = ea.propFix[b] || b, e = ea.propHooks[b]), void 0 !== c ? e && "set" in e && void 0 !== (d = e.set(a, c, b)) ? d : a[b] = c : e && "get" in e && null !== (d = e.get(a, b)) ? d : a[b]
    }, propHooks: {
        tabIndex: {
            get: function (a) {
                var b = ea.find.attr(a, "tabindex");
                return b ? parseInt(b, 10) : Bb.test(a.nodeName) || Cb.test(a.nodeName) && a.href ? 0 : -1
            }
        }
    }
})
```

My first guess would be that the minifier removed the quotes around `for` and that the OneDrive internal browser cannot parse that. Old-school JavaScript versions require quotes around the keys in a JSON object.

**Comment by arothuis** [comment]
I think we can tell Uglify to [quote properties](https://github.com/mishoo/UglifyJS2#beautifier-options), but I can't verify if that will fix the issue for OneDrive. 

Adding the following to our uglify task in our Gulpfile should cover that base:
```
options: {
    beautify: {
        quote_keys: true,
    },
}
```

**Comment by thijskh** [comment]
This is the reported user agent: {Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; Win64; x64; Trident/7.0; .NET4.0C; .NET4.0E)}

**Comment by arothuis** [comment]
Interesting [user agent combination](https://msdn.microsoft.com/en-us/library/ms537503(v=vs.85).aspx), not sure what causes this bug as Trident/7.0 is the MSHTML engine for IE11 (and it works in IE11), but `Mozilla/4.0`, `compatible`, `MSIE 7.0` point to the old days predating IE8.

Anyways, I've [created a branch](https://github.com/OpenConext/OpenConext-engineblock/tree/bugfix/quote-properties-js), based on EB 5.0.0, to be more 'quirky-browser-compatible'. It is a wild guess if this fixes the issue. We did not anticipate dealing with <IE8.

We could try and make the JavaScript more compatible with <IE8, but I the WAYF changes for EB 5.1 already improved our chances of it running correctly.

**Comment by thijskh** [comment]
Thanks. I need to find out if we can somehow reproduce this somewhere else than on production...

**Comment by thijskh** [comment]
Surprisingly, it seems that a Windows Update actually fixed the issue. So no action is needed for now.
