### ISSUE TITLE
PDP client fails in 5.2: 'GuzzleHttp\Http\Client' not found

### ISSUE THREAD

**Issue by thijskh** [OpenConext/OpenConext-engineblock#382]
Invoking a policy decision on EB 5.2.0 fails with:

```
Fatal error: Class 'Guzzle\Http\Client' not found in /opt/openconext/OpenConext-engineblock-5.2.0/app/cache/prod/appProdProjectContainer.php on line 621

A very serious error occurred, it has been logged and sent to the administrator.

ERROR:

array (
  'type' => 1,
  'message' => 'Class \'Guzzle\\Http\\Client\' not found',
  'file' => '/opt/openconext/OpenConext-engineblock-5.2.0/app/cache/prod/appProdProjectContainer.php',
  'line' => 621,
)
```

**Comment by arothuis** [comment]
This issue has likely to do with the [upgrade to Guzzle 6](https://github.com/OpenConext/OpenConext-engineblock/pull/377/commits/29e91d7ef22f482ba1d8e5307b1036e1af13ad66) (namespace: `GuzzleHttp\Guzzle`). 

Note that Guzzle 3 (namespace: `Guzzle\Http`) is also installed on development environments for testing purposes in Symfony (using Goutte).

**Comment by DRvanR** [comment]
After some quick research it seems the culprit is a [misconfiguration][1], this should be `GuzzleHttp\Client`. This was not caught, because [the tests use a mocked PDP server][2] since we cannot reliably provide the server on all environments. While developing, after determining the various responses of the PDP server [to use in tests][3], we made the switch between guzzle versions. Since having the tests and [features][4] in place meant we could speed up development by not using the actual PDP server as that was not available on the CI server and requires configuration management for automated testing in development which is also not available, we apparently never actually used the client all the way through to the guzzle library (the lowest level of outgoing HTTP requests). Hence why we've never caught this - we relied too much on the contract tests.

Lesson:
contract tests are good, but we need some way to actually test integrations like this in integration and system tests, especially for the functional tests where we want to use the full runtime, not stub out external services. This will be even more important considering the roadmap for this year where we want to become even more (partially) dependent on external services for all login requests.

To fix:
Adjust the configuration, verify in development that it is correct, test again in a deployed environment.

[1]: https://github.com/OpenConext/OpenConext-engineblock/blob/c7eae8cc66e02e34b0cb474448c10b60eb78c78d/src/OpenConext/EngineBlockBundle/Resources/config/services.yml#L57
[2]: https://github.com/OpenConext/OpenConext-engineblock/blob/c7eae8cc66e02e34b0cb474448c10b60eb78c78d/tests/unit/OpenConext/EngineBlockBundle/Pdp/PdpClientTest.php#L39-L54
[3]: https://github.com/OpenConext/OpenConext-engineblock/blob/c7eae8cc66e02e34b0cb474448c10b60eb78c78d/tests/unit/OpenConext/EngineBlockBundle/Pdp/PolicyDecisionTest.php
[4]: https://github.com/OpenConext/OpenConext-engineblock/blob/c7eae8cc66e02e34b0cb474448c10b60eb78c78d/src/OpenConext/EngineBlockFunctionalTestingBundle/Features/PolicyEnforcement.feature
