### ISSUE TITLE
Log level for SAML protocol-errors

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/OpenConext-engineblock#821]
I noticed that SAML protocol-level errors are logged at INFO-level:

https://github.com/OpenConext/OpenConext-engineblock/blob/707cd875b13ce70f7209b924722e379f112f6995/library/EngineBlock/Corto/Module/Service/SingleSignOn.php#L185

I guess it's debatable, but I usually don't log INFO messages and these situations are not 'normal operation' in my book (eventhough it's the right thing to do as per spec).
May I suggest this (and similar) case is changed to either NOTICE ('Interesting events') or perhaps even WARNING ('Normal but significant events')?

**Comment by thijskh** [comment]
I would disagree that it’s not normal behaviour. Perfectly fine for an SP to request passive and they must always be prepared that the answer is No, and it’s legitimate and expected that EB will not render a wayf so it’s fine that EB responds this way.

We’ve worked to reduce the amount of noise in warning and error so only actual problems surface. This is just by design that it works this way, so warning is not appropriate.

**Comment by tvdijen** [comment]
OK, I can live with that explanation.. I guess I can just raise the log level to see more detail.

However, in my case the SP is another EB instance showing an 'Identity Provider error' to the user and the actual SP never receives the NoPassive and therefore can't anticipate on it.. Shouldn't the SAML-error be passed through the proxy?
