### ISSUE TITLE
Deprecate urn:oasis:names:tc:SAML:2.0:nameid-format:unspecified

### ISSUE THREAD

**Issue by relaxnow** [OpenConext/OpenConext-engineblock#96]
```
    /**
     * @deprecated This is an incorrect name id format since unspecified does no longer exist in SAML 2.0, only use this for backwards compatibility
     */
    const SAML2_0_NAMEID_FORMAT_UNSPECIFIED = 'urn:oasis:names:tc:SAML:2.0:nameid-format:unspecified';
```

**Comment by thijskh** [comment]
So we discussed it a bit and the change has too much breakage potential to perform just in a single migration. Our plan is to take the list and work through it manually to remove all use of this and/or contact SP's whether they require it. I think the migration should be backed out for the next SR release since this will take some time to get sorted.

**Comment by thijskh** [comment]
This has been eliminated from all our production instances. The format can be removed from EB.
